server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    locations:
      - filesystem:src/main/resources/db/migrations
    encoding: cp1252
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

opentracing:
  jaeger:
    service-name: gestao-vendas
    udp-sender:
      host: localhost
      port: 6831
    sampler-type: const
    sampler-param: 1